# Generated by Django 4.2.23 on 2025-09-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='birthday',
            new_name='comment',
        ),
    ]
