# Generated by Django 5.1.1 on 2026-03-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
